# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Product.destroy_all
Bay.destroy_all

Bay.create(code: "a10", position: 1)
Bay.create(code: "a9", position: 2)
Bay.create(code: "a8", position: 3)
Bay.create(code: "a7", position: 4)
Bay.create(code: "a6", position: 5)
Bay.create(code: "a5", position: 6)
Bay.create(code: "a4", position: 7)
Bay.create(code: "a3", position: 8)
Bay.create(code: "a2", position: 9)
Bay.create(code: "a1", position: 10)
Bay.create(code: "c1", position: 11)
Bay.create(code: "c2", position: 12)
Bay.create(code: "c3", position: 13)
Bay.create(code: "c4", position: 14)
Bay.create(code: "c5", position: 15)
Bay.create(code: "c6", position: 16)
Bay.create(code: "c7", position: 17)
Bay.create(code: "c8", position: 18)
Bay.create(code: "c9", position: 19)
Bay.create(code: "c10", position: 20)
Bay.create(code: "b1", position: 21)
Bay.create(code: "b2", position: 22)
Bay.create(code: "b3", position: 23)
Bay.create(code: "b4", position: 24)
Bay.create(code: "b5", position: 25)
Bay.create(code: "b6", position: 26)
Bay.create(code: "b7", position: 27)
Bay.create(code: "b8", position: 28)
Bay.create(code: "b9", position: 29)
Bay.create(code: "b10", position: 30)

Product.create(name: "bath fizzers", bay: Bay.find_by(code: "b7"))
Product.create(name: "blouse", bay: Bay.find_by(code: "a3"))
Product.create(name: "bookmark", bay: Bay.find_by(code: "a7"))
Product.create(name: "candy wrapper", bay: Bay.find_by(code: "c8"))
Product.create(name: "chalk", bay: Bay.find_by(code: "c3"))
Product.create(name: "cookie jar", bay: Bay.find_by(code: "b10"))
Product.create(name: "deodorant", bay: Bay.find_by(code: "b9"))
Product.create(name: "drill press", bay: Bay.find_by(code: "c2"))
Product.create(name: "face wash", bay: Bay.find_by(code: "c6"))
Product.create(name: "glow stick", bay: Bay.find_by(code: "a9"))
Product.create(name: "hanger", bay: Bay.find_by(code: "a4"))
Product.create(name: "leg warmers", bay: Bay.find_by(code: "c10"))
Product.create(name: "model car", bay: Bay.find_by(code: "a8"))
Product.create(name: "nail filer", bay: Bay.find_by(code: "b5"))
Product.create(name: "needle", bay: Bay.find_by(code: "a1"))
Product.create(name: "paint brush", bay: Bay.find_by(code: "c7"))
Product.create(name: "photo album", bay: Bay.find_by(code: "b4"))
Product.create(name: "picture frame", bay: Bay.find_by(code: "b3"))
Product.create(name: "rubber band", bay: Bay.find_by(code: "a10"))
Product.create(name: "rubber duck", bay: Bay.find_by(code: "a5"))
Product.create(name: "rusty nail", bay: Bay.find_by(code: "c1"))
Product.create(name: "sharpie", bay: Bay.find_by(code: "b2"))
Product.create(name: "shoe lace", bay: Bay.find_by(code: "c9"))
Product.create(name: "shovel", bay: Bay.find_by(code: "a6"))
Product.create(name: "stop sign", bay: Bay.find_by(code: "a2"))
Product.create(name: "thermometer", bay: Bay.find_by(code: "c5"))
Product.create(name: "tyre swing", bay: Bay.find_by(code: "b1"))
Product.create(name: "tissue box", bay: Bay.find_by(code: "b8"))
Product.create(name: "tooth paste", bay: Bay.find_by(code: "b6"))
Product.create(name: "word search", bay: Bay.find_by(code: "c4"))